<?php

namespace Thalvik\SymreliaBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Thalvik\SymreliaBundle\Entity\Article As Article;


class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

	public function getArticle($data) {

		$em = $this->getEntityManager();
		
		if (!empty($data['id'])) {
			$article = $em->getRepository('ThalvikSymreliaBundle:Article')->find($data['id']);
			if ($article !== false) {
				return $article;
			}
		}

		if (!empty($data['slug'])) {
			$article = $em->getRepository('ThalvikSymreliaBundle:Article')->findOneBy(array('slug' => $data['slug']));
			if ($article !== false) {
				return $article;
			}
		}


		return new Article();
	}

	public function saveArticle($article) {

		$em = $this->getEntityManager();

	    if (empty($article->getId())) {
	      $em->persist($article);
	    }

	    $em->flush();
	    
	    return $article;
	}

	public function deleteArticle($id) {

		$em = $this->getEntityManager();

		$article = $em->getRepository('ThalvikSymreliaBundle:Article')->find($id);
		if ($article) {
			$em->remove($article);
        	$em->flush();
		}
		

        return true;
	}
}
